Thumbor 7 (#103)
* updated Dockerfile and docker-entrypoint based on
  https://github.com/MinimalCompact/thumbor/issues/67#issuecomment-592918001
* moving from Semaphore to Github actions
* using thumbor's built-in multiprocess
* taking changes from #101
* moving docker images to Github (ghcr.io)
* updated requirements with some tc (thumbor community) dependencies that support python 3 / thumbor 7
* added multiarch support (thanks @danquack and @mpdude)
* added option to specify THUMBOR_HOST (thanks @roman-stelmakh-emesa)

TODO

* [x] [circus / multiprocess is broken](https://github.com/MinimalCompact/thumbor/issues/67#issuecomment-592954554)
* [x] move dependencies to `requirements.txt` ?
* [x] add more libs to `requirements.txt` (which?)
* [x] is the conf file backwards compatible?
* [x] ModuleNotFoundError: No module named 'urllib2'
* [x] remotecv image isn't created/pushed? @danquack @mpdude ?
* [ ] caching/performance @danquack @mpdude 
* [ ] testing

---

* refs #67 Thumbor 7.0.0a2

* updated Dockerfile and docker-entrypoint based on
  https://github.com/MinimalCompact/thumbor/issues/67#issuecomment-592918001
* updated push, so we will push alpha tags on this branch, but not
  overwriting `latest` (and also semaphore CI)

* fixing procs to 1, to bypass circus issue... tests might pass?

* updated semaphore vars

* Revert "updated semaphore vars"

This reverts commit 354a14fee5c3c85f4bd630d849134ef2bd8a84ed.

* kk-multiprocess build

* updating benchmarks

* merging multiproc + 7a2 => 7a5

* fallback values

* allowing custom commands in entrypoint

* fixed command

* empty commit

* Restore OS packages

* Currently working without using tc-aws

* preparing for thumbor 7.0

* removed proc-requirements copy

* I think we still need envtpl for the config

* moving lib-requirements to requirements

* using python 3.9

* cleanup; switching to nginx-proxy/nginx-proxy (github project moved)

* removed build for deprecated nginx-proxy

* apparently, the docker hub image still uses jwilder...

* update cairosvg

* envtpl version to 0.7.2 to fix AttributeError: module 'jinja2' has no attribute 'contextfunction'

* Create GHA for building

* bump to thumbor 7.4.7 (latest)

* moved requirements to txt ; updated community versions to latest with python3 support

* fixed typos

* added bats tests to github actions

* split bats install and run

* nginx-proxy-cache image might be required for testing

* fixes bats tests (#120)

* refactor github action to run sequentially (#121)

* using build script
* based on https://github.com/MinimalCompact/thumbor/pull/116
  from @danquack (Thank you!)
* one job runs sequentially
* builds and loads
* runs tests
* pushes if branch is master or thumbor-7 (for now) using the build
  script

* testing thumbor-7 push

* removed semaphore ; update push for thumbor-7

* explicit branch names

* adding gha caching

* switching to ghcr.io

* login to ghcr.io

* testing push

* trying explicit username/repo name

* Revert "trying explicit username/repo name"

This reverts commit 4f63c79e8f5d5bf7239f2c903bcbe70b9067ffab.

* Revert "testing push"

This reverts commit 263740caa195b3f145c6fd0cbeafafe880ec136d.

* Revert "Revert "testing push""

This reverts commit b6b95b56859620872e6668ad40ed90ad6030b313.

* fix tags

* removing local tag for push

* change order

* explicit registry name

* another attempt to push to ghcr (using personal access token)

* another attempt with GITHUB_TOKEN

* switching to personal access token

* docker login

* use action

* One more pass at trying to get this to work

* Revert "One more pass at trying to get this to work"

This reverts commit f40ef14a5df47b7bcc9ef87605ca19e22f41fd70.

* Revert "use action"

This reverts commit 39fe3653c49ba3e0ef05748e96bd9614b8505311.

* Revert "docker login"

This reverts commit 4a31dc4ebc5268434ec1b902b1a6d30e0dfd3053.

* Remove Multi Arch support from SIMD (#126)

* Disable multi arch support for SIMD images

* updated docs + recipes for GHCR

* adding retry to tests (setup using docker-compose can be unpredictable)

* local tags for testing

* base tag for testing

* explicitly using :test tags

* improve workflow to login to ghcr only when pushing

* showing available images

* better caching?

* adding more info before running tests about images

* switched from imgur (returns 429) to freeimage.host

* fixes tests with new cached data

* updated docs to remove imgur and use freeimage.host

* Overwrite host address 0.0.0.0 with THUMBOR_HOST (#129)

* Overwrite host address 0.0.0.0 with THUMBOR_HOST

---------

Co-authored-by: Roman Stelmakh <47328012+roman-stelmakh-emesa@users.noreply.github.com>

* refs ghcr.io

* typo

* cleanup circus

* syncing remotecv with explicit thumbor version

* tweak build script to add pull and adjust platform for remotecv

* should fix remotecv problem

---------

Co-authored-by: Yoav <yoav@gingerlime.com>
Co-authored-by: Bernardo Heynemann <heynemann@gmail.com>
Co-authored-by: maximka777 <maksim.borovskij@yandex.ru>
Co-authored-by: Daniel Quackenbush <25692880+danquack@users.noreply.github.com>
Co-authored-by: Roman Stelmakh <47328012+roman-stelmakh-emesa@users.noreply.github.com>