Update thumbor.conf.tpl redis configuration
Add additional redis configuration which is required to use tc_redis

Without it, you get the following error:

  File "/usr/local/lib/python2.7/site-packages/tc_redis/storages/redis_storage.py", line 69, in on_redis_error
    if self.context.config.REDIS_STORAGE_IGNORE_ERRORS is True:
  File "/usr/local/lib/python2.7/site-packages/derpconf/config.py", line 223, in __getattr__
    raise AttributeError(name)
AttributeError: REDIS_STORAGE_IGNORE_ERRORS